version: '3'
services:
  #Database
  mariadb:
    image: sakura/mariadb
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ""
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: manga_tracker
    ports:
      - 3306:3306
  #Backend services
  discovery-server:
    image: sakura/discovery-server
    container_name: discovery-server
    ports:
      - 8761:8761
  user-service:
    image: sakura/user-service
    depends_on:
      - discovery-server
      - mariadb
    environment:
      - SERVICE_URL_DEFAULT_ZONE=http://discovery-server:8761/eureka/
      - MYSQL_HOST=mariadb
      - EUREKA_INSTANCE_HOSTNAME=user-service
      - EUREKA_INSTANCE_IP_ADDRESS=user-service
    ports:
      - 8082:8082
  manga-info-service:
    image: sakura/manga-info-service
    depends_on:
      - discovery-server
    environment:
      - SERVICE_URL_DEFAULT_ZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=manga-info-service
      - EUREKA_INSTANCE_IP_ADDRESS=manga-info-service
    ports:
      - 8081:8081
  manga-tracker:
    image: sakura/manga-tracker
    depends_on:
      - discovery-server
      - user-service
      - manga-info-service
    environment:
      - SERVICE_URL_DEFAULT_ZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=manga-tracker
      - EUREKA_INSTANCE_IP_ADDRESS=manga-tracker
    ports:
      - 8080:8080
  #Frontend: Angular app
  mangatracker-ng:
    image: sakura/mangatracker-ng
    depends_on:
      - manga-tracker
    ports:
      - 80:80
  #Alermanager
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./metrics/alertmanager:/configs
    command:
      - '--config.file=/configs/alertmanager.yml'
  #Prometheus
  prometheus:
    image: prom/prometheus
    depends_on:
      - manga-tracker
      - alertmanager
    ports:
      - 9090:9090
    volumes:
      - ./metrics/prometheus:/configs
    command:
      - '--config.file=/configs/prometheus.yml'
  # Grafana
  grafana:
    image: grafana/grafana
    depends_on: 
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./metrics/grafana/provisioning:/etc/grafana/provisioning
    
