global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: '<TO_EMAIL>'
    from: '<FROM_EMAIL>'
    smarthost: smtp.gmail.com:587
    auth_username: '<EMAIL>'
    auth_identity: '<EMAIL>'
    auth_password: '<AUTH_KEY>'
  